# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-17 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmacourseenrollment',
            name='student_grade',
            field=models.FloatField(default=0),
        ),
    ]
