# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-17 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma_apps', '0002_tmacourseenrollment_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmacourseenrollment',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
