# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-18 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tma_apps', '0005_auto_20190118_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmacourseenrollment',
            name='course_enrollment_edx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.CourseEnrollment', unique=True),
        ),
        migrations.AlterField(
            model_name='tmacourseoverview',
            name='course_overview_edx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_overviews.CourseOverview', unique=True),
        ),
    ]
