# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-18 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma_apps', '0006_auto_20190118_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmacourseoverview',
            name='is_course_graded',
            field=models.BooleanField(default=True),
        ),
    ]
