# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma_apps', '0007_tmacourseoverview_is_course_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmacourseenrollment',
            name='quiz_completion_rate',
            field=models.FloatField(default=0),
        ),
    ]
