# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma_apps', '0008_tmacourseenrollment_quiz_completion_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmacourseenrollment',
            name='has_displayed_message',
            field=models.BooleanField(default=False),
        ),
    ]
