# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-30 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma_apps', '0010_tmacourseoverview_active_enrollments_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmacourseoverview',
            name='tag',
            field=models.CharField(db_index=True, default=False, max_length=30),
        ),
    ]
