# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-30 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma_apps', '0011_tmacourseoverview_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmacourseoverview',
            name='tag',
            field=models.CharField(db_index=True, default=None, max_length=30),
        ),
    ]
