# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-01 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma_apps', '0012_auto_20190130_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmacourseoverview',
            name='tag',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
