# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-26 10:58
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tma_apps', '0014_auto_20190226_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmacourseoverview',
            name='course_about',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
