# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-28 10:12
from __future__ import unicode_literals

import collections
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tma_apps', '0015_auto_20190226_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmacourseoverview',
            name='course_about',
            field=jsonfield.fields.JSONField(default=collections.OrderedDict),
        ),
        migrations.AlterField(
            model_name='tmacourseoverview',
            name='tag',
            field=models.CharField(db_index=True, default=False, max_length=50),
        ),
    ]
