# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-05 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma_apps', '0016_auto_20190228_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmacourseoverview',
            name='has_menu',
            field=models.BooleanField(default=True),
        ),
    ]
