# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-06 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma_apps', '0017_tmacourseoverview_has_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmacourseoverview',
            name='course_about',
            field=models.TextField(blank=True),
        ),
    ]
