# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-14 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma_apps', '0018_auto_20190306_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmacourseoverview',
            name='onboarding',
            field=models.CharField(db_index=True, default=False, max_length=50),
        ),
    ]
