# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-28 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma_apps', '0019_tmacourseoverview_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmacourseoverview',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
