# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-27 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma_apps', '0021_auto_20190528_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmacourseoverview',
            name='is_linear',
            field=models.BooleanField(default=False),
        ),
    ]
