# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-18 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tma_apps', '0022_tmacourseoverview_is_linear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmacourseoverview',
            name='is_vodeclic',
        ),
    ]
