# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-10 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_overviews', '0014_courseoverview_certificate_available_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TmaProgramCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_overviews.CourseOverview', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TmaProgramEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('has_started_program', models.BooleanField(default=False)),
                ('has_validated_program', models.BooleanField(default=False)),
                ('program_completion_rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TmaProgramOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager_only', models.BooleanField(default=False)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_linear', models.BooleanField(default=False)),
                ('invitation_only', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('program_start_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('program_due_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('program_name', models.CharField(default=b'program name', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tmaprogramenrollment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tma_cms_apps.TmaProgramOverview', unique=True),
        ),
        migrations.AddField(
            model_name='tmaprogramenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tmaprogramcourse',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tma_cms_apps.TmaProgramEnrollment', unique=True),
        ),
    ]
