# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-29 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tma_cms_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmaprogramcourse',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tma_cms_apps.TmaProgramOverview'),
        ),
        migrations.AlterField(
            model_name='tmaprogramenrollment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tma_cms_apps.TmaProgramOverview'),
        ),
    ]
