# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-04 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tma_cms_apps', '0002_auto_20200729_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmaprogramoverview',
            name='program_due_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmaprogramoverview',
            name='program_start_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
