# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-11 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20190117_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_field',
            field=models.TextField(default=b''),
        ),
    ]
